//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Act_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Act_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/visio/2003/core}NamedIndexedRow_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Menu" type="{http://schemas.microsoft.com/visio/2003/core}Menu_Type" minOccurs="0"/>
 *         &lt;element name="Action" type="{http://schemas.microsoft.com/visio/2003/core}Action_Type" minOccurs="0"/>
 *         &lt;element name="Checked" type="{http://schemas.microsoft.com/visio/2003/core}Checked_Type" minOccurs="0"/>
 *         &lt;element name="Disabled" type="{http://schemas.microsoft.com/visio/2003/core}Disabled_Type" minOccurs="0"/>
 *         &lt;element name="ReadOnly" type="{http://schemas.microsoft.com/visio/2003/core}ReadOnly_Type" minOccurs="0"/>
 *         &lt;element name="Invisible" type="{http://schemas.microsoft.com/visio/2003/core}Invisible_Type" minOccurs="0"/>
 *         &lt;element name="BeginGroup" type="{http://schemas.microsoft.com/visio/2003/core}BeginGroup_Type" minOccurs="0"/>
 *         &lt;element name="TagName" type="{http://schemas.microsoft.com/visio/2003/core}TagName_Type" minOccurs="0"/>
 *         &lt;element name="ButtonFace" type="{http://schemas.microsoft.com/visio/2003/core}ButtonFace_Type" minOccurs="0"/>
 *         &lt;element name="SortKey" type="{http://schemas.microsoft.com/visio/2003/core}SortKey_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Act_Type", propOrder = {
    "menuOrActionOrChecked"
})
public class ActType
    extends NamedIndexedRowType
{

    @XmlElements({
        @XmlElement(name = "Menu", type = MenuType.class),
        @XmlElement(name = "Action", type = ActionType.class),
        @XmlElement(name = "Checked", type = CheckedType.class),
        @XmlElement(name = "Disabled", type = DisabledType.class),
        @XmlElement(name = "ReadOnly", type = ReadOnlyType.class),
        @XmlElement(name = "Invisible", type = InvisibleType.class),
        @XmlElement(name = "BeginGroup", type = BeginGroupType.class),
        @XmlElement(name = "TagName", type = TagNameType.class),
        @XmlElement(name = "ButtonFace", type = ButtonFaceType.class),
        @XmlElement(name = "SortKey", type = SortKeyType.class)
    })
    protected List<CellType> menuOrActionOrChecked;

    /**
     * Gets the value of the menuOrActionOrChecked property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menuOrActionOrChecked property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenuOrActionOrChecked().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MenuType }
     * {@link ActionType }
     * {@link CheckedType }
     * {@link DisabledType }
     * {@link ReadOnlyType }
     * {@link InvisibleType }
     * {@link BeginGroupType }
     * {@link TagNameType }
     * {@link ButtonFaceType }
     * {@link SortKeyType }
     * 
     * 
     */
    public List<CellType> getMenuOrActionOrChecked() {
        if (menuOrActionOrChecked == null) {
            menuOrActionOrChecked = new ArrayList<CellType>();
        }
        return this.menuOrActionOrChecked;
    }

}
