//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Connect_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Connect_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FromSheet" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="FromCell" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FromPart" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ToSheet" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="ToCell" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ToPart" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Connect_Type")
public class ConnectType {

    @XmlAttribute(name = "FromSheet")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger fromSheet;
    @XmlAttribute(name = "FromCell")
    protected String fromCell;
    @XmlAttribute(name = "FromPart")
    protected Integer fromPart;
    @XmlAttribute(name = "ToSheet")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger toSheet;
    @XmlAttribute(name = "ToCell")
    protected String toCell;
    @XmlAttribute(name = "ToPart")
    protected Integer toPart;

    /**
     * Gets the value of the fromSheet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFromSheet() {
        return fromSheet;
    }

    /**
     * Sets the value of the fromSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFromSheet(BigInteger value) {
        this.fromSheet = value;
    }

    /**
     * Gets the value of the fromCell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCell() {
        return fromCell;
    }

    /**
     * Sets the value of the fromCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCell(String value) {
        this.fromCell = value;
    }

    /**
     * Gets the value of the fromPart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFromPart() {
        return fromPart;
    }

    /**
     * Sets the value of the fromPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFromPart(Integer value) {
        this.fromPart = value;
    }

    /**
     * Gets the value of the toSheet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getToSheet() {
        return toSheet;
    }

    /**
     * Sets the value of the toSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setToSheet(BigInteger value) {
        this.toSheet = value;
    }

    /**
     * Gets the value of the toCell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCell() {
        return toCell;
    }

    /**
     * Sets the value of the toCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCell(String value) {
        this.toCell = value;
    }

    /**
     * Gets the value of the toPart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getToPart() {
        return toPart;
    }

    /**
     * Sets the value of the toPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setToPart(Integer value) {
        this.toPart = value;
    }

}
