//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FontEntry_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FontEntry_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CharSet" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="PitchAndFamily" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="Attributes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="Weight" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="Unicode" type="{http://schemas.microsoft.com/visio/2003/core}ISOBoolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FontEntry_Type")
public class FontEntryType {

    @XmlAttribute(name = "ID")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "CharSet")
    @XmlSchemaType(name = "unsignedByte")
    protected Short charSet;
    @XmlAttribute(name = "PitchAndFamily")
    @XmlSchemaType(name = "unsignedByte")
    protected Short pitchAndFamily;
    @XmlAttribute(name = "Attributes")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer attributes;
    @XmlAttribute(name = "Weight")
    protected Long weight;
    @XmlAttribute(name = "Unicode")
    protected BigInteger unicode;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the charSet property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCharSet() {
        return charSet;
    }

    /**
     * Sets the value of the charSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCharSet(Short value) {
        this.charSet = value;
    }

    /**
     * Gets the value of the pitchAndFamily property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPitchAndFamily() {
        return pitchAndFamily;
    }

    /**
     * Sets the value of the pitchAndFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPitchAndFamily(Short value) {
        this.pitchAndFamily = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttributes(Integer value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWeight(Long value) {
        this.weight = value;
    }

    /**
     * Gets the value of the unicode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnicode() {
        return unicode;
    }

    /**
     * Sets the value of the unicode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnicode(BigInteger value) {
        this.unicode = value;
    }

}
