//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ForeignData_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ForeignData_Type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="ForeignType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ObjectType" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="ShowAsIcon" type="{http://schemas.microsoft.com/visio/2003/core}ISOBoolean" />
 *       &lt;attribute name="ObjectWidth" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="ObjectHeight" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="MappingMode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="ExtentX" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="ExtentY" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="CompressionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CompressionLevel" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForeignData_Type", propOrder = {
    "value"
})
public class ForeignDataType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ForeignType")
    protected String foreignType;
    @XmlAttribute(name = "ObjectType")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger objectType;
    @XmlAttribute(name = "ShowAsIcon")
    protected BigInteger showAsIcon;
    @XmlAttribute(name = "ObjectWidth")
    protected Float objectWidth;
    @XmlAttribute(name = "ObjectHeight")
    protected Float objectHeight;
    @XmlAttribute(name = "MappingMode")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer mappingMode;
    @XmlAttribute(name = "ExtentX")
    protected Float extentX;
    @XmlAttribute(name = "ExtentY")
    protected Float extentY;
    @XmlAttribute(name = "CompressionType")
    protected String compressionType;
    @XmlAttribute(name = "CompressionLevel")
    protected Float compressionLevel;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the foreignType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignType() {
        return foreignType;
    }

    /**
     * Sets the value of the foreignType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignType(String value) {
        this.foreignType = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectType(BigInteger value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the showAsIcon property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShowAsIcon() {
        return showAsIcon;
    }

    /**
     * Sets the value of the showAsIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShowAsIcon(BigInteger value) {
        this.showAsIcon = value;
    }

    /**
     * Gets the value of the objectWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getObjectWidth() {
        return objectWidth;
    }

    /**
     * Sets the value of the objectWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setObjectWidth(Float value) {
        this.objectWidth = value;
    }

    /**
     * Gets the value of the objectHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getObjectHeight() {
        return objectHeight;
    }

    /**
     * Sets the value of the objectHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setObjectHeight(Float value) {
        this.objectHeight = value;
    }

    /**
     * Gets the value of the mappingMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMappingMode() {
        return mappingMode;
    }

    /**
     * Sets the value of the mappingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMappingMode(Integer value) {
        this.mappingMode = value;
    }

    /**
     * Gets the value of the extentX property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getExtentX() {
        return extentX;
    }

    /**
     * Sets the value of the extentX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setExtentX(Float value) {
        this.extentX = value;
    }

    /**
     * Gets the value of the extentY property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getExtentY() {
        return extentY;
    }

    /**
     * Sets the value of the extentY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setExtentY(Float value) {
        this.extentY = value;
    }

    /**
     * Gets the value of the compressionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompressionType() {
        return compressionType;
    }

    /**
     * Sets the value of the compressionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompressionType(String value) {
        this.compressionType = value;
    }

    /**
     * Gets the value of the compressionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCompressionLevel() {
        return compressionLevel;
    }

    /**
     * Sets the value of the compressionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCompressionLevel(Float value) {
        this.compressionLevel = value;
    }

}
