//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Foreign_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Foreign_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/visio/2003/core}Row_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ImgOffsetX" type="{http://schemas.microsoft.com/visio/2003/core}ImgOffsetX_Type" minOccurs="0"/>
 *         &lt;element name="ImgOffsetY" type="{http://schemas.microsoft.com/visio/2003/core}ImgOffsetY_Type" minOccurs="0"/>
 *         &lt;element name="ImgWidth" type="{http://schemas.microsoft.com/visio/2003/core}ImgWidth_Type" minOccurs="0"/>
 *         &lt;element name="ImgHeight" type="{http://schemas.microsoft.com/visio/2003/core}ImgHeight_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Foreign_Type", propOrder = {
    "imgOffsetXOrImgOffsetYOrImgWidth"
})
public class ForeignType
    extends RowType
{

    @XmlElements({
        @XmlElement(name = "ImgOffsetX", type = ImgOffsetXType.class),
        @XmlElement(name = "ImgOffsetY", type = ImgOffsetYType.class),
        @XmlElement(name = "ImgWidth", type = ImgWidthType.class),
        @XmlElement(name = "ImgHeight", type = ImgHeightType.class)
    })
    protected List<CellType> imgOffsetXOrImgOffsetYOrImgWidth;

    /**
     * Gets the value of the imgOffsetXOrImgOffsetYOrImgWidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imgOffsetXOrImgOffsetYOrImgWidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImgOffsetXOrImgOffsetYOrImgWidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImgOffsetXType }
     * {@link ImgOffsetYType }
     * {@link ImgWidthType }
     * {@link ImgHeightType }
     * 
     * 
     */
    public List<CellType> getImgOffsetXOrImgOffsetYOrImgWidth() {
        if (imgOffsetXOrImgOffsetYOrImgWidth == null) {
            imgOffsetXOrImgOffsetYOrImgWidth = new ArrayList<CellType>();
        }
        return this.imgOffsetXOrImgOffsetYOrImgWidth;
    }

}
