//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Geom_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Geom_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/visio/2003/core}GeomSection_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="NoFill" type="{http://schemas.microsoft.com/visio/2003/core}NoFill_Type" minOccurs="0"/>
 *         &lt;element name="NoLine" type="{http://schemas.microsoft.com/visio/2003/core}NoLine_Type" minOccurs="0"/>
 *         &lt;element name="NoShow" type="{http://schemas.microsoft.com/visio/2003/core}NoShow_Type" minOccurs="0"/>
 *         &lt;element name="NoSnap" type="{http://schemas.microsoft.com/visio/2003/core}NoSnap_Type" minOccurs="0"/>
 *         &lt;element name="MoveTo" type="{http://schemas.microsoft.com/visio/2003/core}MoveTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LineTo" type="{http://schemas.microsoft.com/visio/2003/core}LineTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ArcTo" type="{http://schemas.microsoft.com/visio/2003/core}ArcTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InfiniteLine" type="{http://schemas.microsoft.com/visio/2003/core}InfiniteLine_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Ellipse" type="{http://schemas.microsoft.com/visio/2003/core}Ellipse_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EllipticalArcTo" type="{http://schemas.microsoft.com/visio/2003/core}EllipticalArcTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SplineStart" type="{http://schemas.microsoft.com/visio/2003/core}SplineStart_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SplineKnot" type="{http://schemas.microsoft.com/visio/2003/core}SplineKnot_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PolylineTo" type="{http://schemas.microsoft.com/visio/2003/core}PolylineTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NURBSTo" type="{http://schemas.microsoft.com/visio/2003/core}NURBSTo_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Geom_Type", propOrder = {
    "noFillOrNoLineOrNoShow"
})
public class GeomType
    extends GeomSectionType
{

    @XmlElements({
        @XmlElement(name = "NoFill", type = NoFillType.class),
        @XmlElement(name = "NoLine", type = NoLineType.class),
        @XmlElement(name = "NoShow", type = NoShowType.class),
        @XmlElement(name = "NoSnap", type = NoSnapType.class),
        @XmlElement(name = "MoveTo", type = MoveToType.class),
        @XmlElement(name = "LineTo", type = LineToType.class),
        @XmlElement(name = "ArcTo", type = ArcToType.class),
        @XmlElement(name = "InfiniteLine", type = InfiniteLineType.class),
        @XmlElement(name = "Ellipse", type = EllipseType.class),
        @XmlElement(name = "EllipticalArcTo", type = EllipticalArcToType.class),
        @XmlElement(name = "SplineStart", type = SplineStartType.class),
        @XmlElement(name = "SplineKnot", type = SplineKnotType.class),
        @XmlElement(name = "PolylineTo", type = PolylineToType.class),
        @XmlElement(name = "NURBSTo", type = NURBSToType.class)
    })
    protected List<Object> noFillOrNoLineOrNoShow;

    /**
     * Gets the value of the noFillOrNoLineOrNoShow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noFillOrNoLineOrNoShow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoFillOrNoLineOrNoShow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoFillType }
     * {@link NoLineType }
     * {@link NoShowType }
     * {@link NoSnapType }
     * {@link MoveToType }
     * {@link LineToType }
     * {@link ArcToType }
     * {@link InfiniteLineType }
     * {@link EllipseType }
     * {@link EllipticalArcToType }
     * {@link SplineStartType }
     * {@link SplineKnotType }
     * {@link PolylineToType }
     * {@link NURBSToType }
     * 
     * 
     */
    public List<Object> getNoFillOrNoLineOrNoShow() {
        if (noFillOrNoLineOrNoShow == null) {
            noFillOrNoLineOrNoShow = new ArrayList<Object>();
        }
        return this.noFillOrNoLineOrNoShow;
    }

}
