//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:16 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Windows_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Windows_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Window" type="{http://schemas.microsoft.com/visio/2003/core}Window_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ClientWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="ClientHeight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Windows_Type", propOrder = {
    "window"
})
public class WindowsType {

    @XmlElement(name = "Window")
    protected List<WindowType> window;
    @XmlAttribute(name = "ClientWidth")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer clientWidth;
    @XmlAttribute(name = "ClientHeight")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer clientHeight;

    /**
     * Gets the value of the window property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the window property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWindow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WindowType }
     * 
     * 
     */
    public List<WindowType> getWindow() {
        if (window == null) {
            window = new ArrayList<WindowType>();
        }
        return this.window;
    }

    /**
     * Gets the value of the clientWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClientWidth() {
        return clientWidth;
    }

    /**
     * Sets the value of the clientWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClientWidth(Integer value) {
        this.clientWidth = value;
    }

    /**
     * Gets the value of the clientHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClientHeight() {
        return clientHeight;
    }

    /**
     * Sets the value of the clientHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClientHeight(Integer value) {
        this.clientHeight = value;
    }

}
