//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:03:08 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Image_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Image_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/visio/2010/extension}Row_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Gamma" type="{http://schemas.microsoft.com/office/visio/2010/extension}Gamma_Type" minOccurs="0"/>
 *         &lt;element name="Contrast" type="{http://schemas.microsoft.com/office/visio/2010/extension}Contrast_Type" minOccurs="0"/>
 *         &lt;element name="Brightness" type="{http://schemas.microsoft.com/office/visio/2010/extension}Brightness_Type" minOccurs="0"/>
 *         &lt;element name="Sharpen" type="{http://schemas.microsoft.com/office/visio/2010/extension}Sharpen_Type" minOccurs="0"/>
 *         &lt;element name="Blur" type="{http://schemas.microsoft.com/office/visio/2010/extension}Blur_Type" minOccurs="0"/>
 *         &lt;element name="Denoise" type="{http://schemas.microsoft.com/office/visio/2010/extension}Denoise_Type" minOccurs="0"/>
 *         &lt;element name="Transparency" type="{http://schemas.microsoft.com/office/visio/2010/extension}Transparency_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image_Type", propOrder = {
    "gammaOrContrastOrBrightness"
})
public class ImageType
    extends RowType
{

    @XmlElements({
        @XmlElement(name = "Gamma", type = GammaType.class),
        @XmlElement(name = "Contrast", type = ContrastType.class),
        @XmlElement(name = "Brightness", type = BrightnessType.class),
        @XmlElement(name = "Sharpen", type = SharpenType.class),
        @XmlElement(name = "Blur", type = BlurType.class),
        @XmlElement(name = "Denoise", type = DenoiseType.class),
        @XmlElement(name = "Transparency", type = TransparencyType.class)
    })
    protected List<CellType> gammaOrContrastOrBrightness;

    /**
     * Gets the value of the gammaOrContrastOrBrightness property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gammaOrContrastOrBrightness property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGammaOrContrastOrBrightness().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GammaType }
     * {@link ContrastType }
     * {@link BrightnessType }
     * {@link SharpenType }
     * {@link BlurType }
     * {@link DenoiseType }
     * {@link TransparencyType }
     * 
     * 
     */
    public List<CellType> getGammaOrContrastOrBrightness() {
        if (gammaOrContrastOrBrightness == null) {
            gammaOrContrastOrBrightness = new ArrayList<CellType>();
        }
        return this.gammaOrContrastOrBrightness;
    }

}
