//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:03:08 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Line_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Line_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/visio/2010/extension}Row_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="LineWeight" type="{http://schemas.microsoft.com/office/visio/2010/extension}LineWeight_Type" minOccurs="0"/>
 *         &lt;element name="LineColor" type="{http://schemas.microsoft.com/office/visio/2010/extension}LineColor_Type" minOccurs="0"/>
 *         &lt;element name="LinePattern" type="{http://schemas.microsoft.com/office/visio/2010/extension}LinePattern_Type" minOccurs="0"/>
 *         &lt;element name="Rounding" type="{http://schemas.microsoft.com/office/visio/2010/extension}Rounding_Type" minOccurs="0"/>
 *         &lt;element name="EndArrowSize" type="{http://schemas.microsoft.com/office/visio/2010/extension}EndArrowSize_Type" minOccurs="0"/>
 *         &lt;element name="BeginArrow" type="{http://schemas.microsoft.com/office/visio/2010/extension}BeginArrow_Type" minOccurs="0"/>
 *         &lt;element name="EndArrow" type="{http://schemas.microsoft.com/office/visio/2010/extension}EndArrow_Type" minOccurs="0"/>
 *         &lt;element name="LineCap" type="{http://schemas.microsoft.com/office/visio/2010/extension}LineCap_Type" minOccurs="0"/>
 *         &lt;element name="BeginArrowSize" type="{http://schemas.microsoft.com/office/visio/2010/extension}BeginArrowSize_Type" minOccurs="0"/>
 *         &lt;element name="LineColorTrans" type="{http://schemas.microsoft.com/office/visio/2010/extension}LineColorTrans_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Line_Type", propOrder = {
    "lineWeightOrLineColorOrLinePattern"
})
public class LineType
    extends RowType
{

    @XmlElements({
        @XmlElement(name = "LineWeight", type = LineWeightType.class),
        @XmlElement(name = "LineColor", type = LineColorType.class),
        @XmlElement(name = "LinePattern", type = LinePatternType.class),
        @XmlElement(name = "Rounding", type = RoundingType.class),
        @XmlElement(name = "EndArrowSize", type = EndArrowSizeType.class),
        @XmlElement(name = "BeginArrow", type = BeginArrowType.class),
        @XmlElement(name = "EndArrow", type = EndArrowType.class),
        @XmlElement(name = "LineCap", type = LineCapType.class),
        @XmlElement(name = "BeginArrowSize", type = BeginArrowSizeType.class),
        @XmlElement(name = "LineColorTrans", type = LineColorTransType.class)
    })
    protected List<CellType> lineWeightOrLineColorOrLinePattern;

    /**
     * Gets the value of the lineWeightOrLineColorOrLinePattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineWeightOrLineColorOrLinePattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineWeightOrLineColorOrLinePattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineWeightType }
     * {@link LineColorType }
     * {@link LinePatternType }
     * {@link RoundingType }
     * {@link EndArrowSizeType }
     * {@link BeginArrowType }
     * {@link EndArrowType }
     * {@link LineCapType }
     * {@link BeginArrowSizeType }
     * {@link LineColorTransType }
     * 
     * 
     */
    public List<CellType> getLineWeightOrLineColorOrLinePattern() {
        if (lineWeightOrLineColorOrLinePattern == null) {
            lineWeightOrLineColorOrLinePattern = new ArrayList<CellType>();
        }
        return this.lineWeightOrLineColorOrLinePattern;
    }

}
