//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:03:08 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Prop_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Prop_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/visio/2010/extension}NamedRow_Type">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Value" type="{http://schemas.microsoft.com/office/visio/2010/extension}Value_Type" minOccurs="0"/>
 *         &lt;element name="Prompt" type="{http://schemas.microsoft.com/office/visio/2010/extension}Prompt_Type" minOccurs="0"/>
 *         &lt;element name="Label" type="{http://schemas.microsoft.com/office/visio/2010/extension}Label_Type" minOccurs="0"/>
 *         &lt;element name="Format" type="{http://schemas.microsoft.com/office/visio/2010/extension}Format_Type" minOccurs="0"/>
 *         &lt;element name="SortKey" type="{http://schemas.microsoft.com/office/visio/2010/extension}SortKey_Type" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://schemas.microsoft.com/office/visio/2010/extension}Type_Type" minOccurs="0"/>
 *         &lt;element name="Invisible" type="{http://schemas.microsoft.com/office/visio/2010/extension}Invisible_Type" minOccurs="0"/>
 *         &lt;element name="Verify" type="{http://schemas.microsoft.com/office/visio/2010/extension}Verify_Type" minOccurs="0"/>
 *         &lt;element name="LangID" type="{http://schemas.microsoft.com/office/visio/2010/extension}LangID_Type" minOccurs="0"/>
 *         &lt;element name="Calendar" type="{http://schemas.microsoft.com/office/visio/2010/extension}Calendar_Type" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Prop_Type", propOrder = {
    "valueOrPromptOrLabel"
})
public class PropType
    extends NamedRowType
{

    @XmlElements({
        @XmlElement(name = "Value", type = ValueType.class),
        @XmlElement(name = "Prompt", type = PromptType.class),
        @XmlElement(name = "Label", type = LabelType.class),
        @XmlElement(name = "Format", type = FormatType.class),
        @XmlElement(name = "SortKey", type = SortKeyType.class),
        @XmlElement(name = "Type", type = TypeType.class),
        @XmlElement(name = "Invisible", type = InvisibleType.class),
        @XmlElement(name = "Verify", type = VerifyType.class),
        @XmlElement(name = "LangID", type = LangIDType.class),
        @XmlElement(name = "Calendar", type = CalendarType.class)
    })
    protected List<Object> valueOrPromptOrLabel;

    /**
     * Gets the value of the valueOrPromptOrLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueOrPromptOrLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueOrPromptOrLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueType }
     * {@link PromptType }
     * {@link LabelType }
     * {@link FormatType }
     * {@link SortKeyType }
     * {@link TypeType }
     * {@link InvisibleType }
     * {@link VerifyType }
     * {@link LangIDType }
     * {@link CalendarType }
     * 
     * 
     */
    public List<Object> getValueOrPromptOrLabel() {
        if (valueOrPromptOrLabel == null) {
            valueOrPromptOrLabel = new ArrayList<Object>();
        }
        return this.valueOrPromptOrLabel;
    }

}
