//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:03:08 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2010;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rule_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rule_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RuleFilter" type="{http://schemas.microsoft.com/office/visio/2010/extension}RuleFilter_Type" minOccurs="0"/>
 *         &lt;element name="RuleTest" type="{http://schemas.microsoft.com/office/visio/2010/extension}RuleTest_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="NameU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RuleTarget" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Ignored" type="{http://schemas.microsoft.com/office/visio/2010/extension}ISOBoolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rule_Type", propOrder = {
    "ruleFilter",
    "ruleTest"
})
public class RuleType {

    @XmlElement(name = "RuleFilter")
    protected RuleFilterType ruleFilter;
    @XmlElement(name = "RuleTest")
    protected RuleTestType ruleTest;
    @XmlAttribute(name = "ID")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;
    @XmlAttribute(name = "NameU")
    protected String nameU;
    @XmlAttribute(name = "Category")
    protected String category;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "RuleTarget")
    protected Integer ruleTarget;
    @XmlAttribute(name = "Ignored")
    protected BigInteger ignored;

    /**
     * Gets the value of the ruleFilter property.
     * 
     * @return
     *     possible object is
     *     {@link RuleFilterType }
     *     
     */
    public RuleFilterType getRuleFilter() {
        return ruleFilter;
    }

    /**
     * Sets the value of the ruleFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleFilterType }
     *     
     */
    public void setRuleFilter(RuleFilterType value) {
        this.ruleFilter = value;
    }

    /**
     * Gets the value of the ruleTest property.
     * 
     * @return
     *     possible object is
     *     {@link RuleTestType }
     *     
     */
    public RuleTestType getRuleTest() {
        return ruleTest;
    }

    /**
     * Sets the value of the ruleTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleTestType }
     *     
     */
    public void setRuleTest(RuleTestType value) {
        this.ruleTest = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the nameU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameU() {
        return nameU;
    }

    /**
     * Sets the value of the nameU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameU(String value) {
        this.nameU = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ruleTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRuleTarget() {
        return ruleTarget;
    }

    /**
     * Sets the value of the ruleTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRuleTarget(Integer value) {
        this.ruleTarget = value;
    }

    /**
     * Gets the value of the ignored property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIgnored() {
        return ignored;
    }

    /**
     * Sets the value of the ignored property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIgnored(BigInteger value) {
        this.ignored = value;
    }

}
