//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:03:08 PM BST 
//


package uk.org.whitecottage.visio.jaxb.visio2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Validation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Validation_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidationProperties" type="{http://schemas.microsoft.com/office/visio/2010/extension}ValidationProperties_Type" minOccurs="0"/>
 *         &lt;element name="RuleSets" type="{http://schemas.microsoft.com/office/visio/2010/extension}RuleSets_Type" minOccurs="0"/>
 *         &lt;element name="Issues" type="{http://schemas.microsoft.com/office/visio/2010/extension}Issues_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Validation_Type", propOrder = {
    "validationProperties",
    "ruleSets",
    "issues"
})
public class ValidationType {

    @XmlElement(name = "ValidationProperties")
    protected ValidationPropertiesType validationProperties;
    @XmlElement(name = "RuleSets")
    protected RuleSetsType ruleSets;
    @XmlElement(name = "Issues")
    protected IssuesType issues;

    /**
     * Gets the value of the validationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationPropertiesType }
     *     
     */
    public ValidationPropertiesType getValidationProperties() {
        return validationProperties;
    }

    /**
     * Sets the value of the validationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationPropertiesType }
     *     
     */
    public void setValidationProperties(ValidationPropertiesType value) {
        this.validationProperties = value;
    }

    /**
     * Gets the value of the ruleSets property.
     * 
     * @return
     *     possible object is
     *     {@link RuleSetsType }
     *     
     */
    public RuleSetsType getRuleSets() {
        return ruleSets;
    }

    /**
     * Sets the value of the ruleSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleSetsType }
     *     
     */
    public void setRuleSets(RuleSetsType value) {
        this.ruleSets = value;
    }

    /**
     * Gets the value of the issues property.
     * 
     * @return
     *     possible object is
     *     {@link IssuesType }
     *     
     */
    public IssuesType getIssues() {
        return issues;
    }

    /**
     * Sets the value of the issues property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuesType }
     *     
     */
    public void setIssues(IssuesType value) {
        this.issues = value;
    }

}
