//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 04:02:41 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/visio/2006/extension", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.org.whitecottage.visio.jaxb.visio2007;
